//
// Created by Brandon Hargitay on 11/22/22.
//

#ifndef CLASSEXAMPLE1122_TEXTUREENUM_H
#define CLASSEXAMPLE1122_TEXTUREENUM_H
enum textureEnum{
    ROCKET,
    ROCKET2,
    ASTEROIDS,
    ASTEROIDPIXEL,
    BACKGROUND,
    BULLET,
    HEART,
    LAST_TEXTURE
};
#endif //CLASSEXAMPLE1122_TEXTUREENUM_H
